# kempt configuration: https://github.com/ZacSweers/kempt
# Run `kempt --help` to see all options.

[ktfmt]
version = "0.64"
style = "google"

[license-header]
file = "config/license-header.txt"

[ktfmt.license-header]
excludes = "config/license-header-excludes-kt.txt"

[hook]
mode = "check"
