# Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Android
android.lint.useK2Uast=true

# AndroidX flags
android.useAndroidX=true
android.newDsl=true
android.builtInKotlin=true
android.disallowKotlinSourceSets=true

# Kotlin flags
kotlin.mpp.enableCInteropCommonizer=true
kotlin.native.enableKlibsCrossCompilation=true
kotlin.native.ignoreDisabledTargets=true

# Compose Multiplatform experimental target flags
org.jetbrains.compose.experimental.jscanvas.enabled=true
org.jetbrains.compose.experimental.macos.enabled=true
org.jetbrains.compose.experimental.wasm.enabled=true

# Version
GROUP=me.stagg.retainx
VERSION_NAME=0.1.0-SNAPSHOT
POM_URL=https://github.com/stagg/retainx/
POM_SCM_URL=https://github.com/stagg/retainx/
POM_SCM_CONNECTION=scm:git:git://github.com/stagg/retainx.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/stagg/retainx.git
POM_LICENCE_NAME=MIT License
POM_LICENCE_URL=https://github.com/stagg/retainx/blob/main/LICENSE
POM_LICENCE_DIST=repo
POM_DEVELOPER_ID=stagg
POM_DEVELOPER_NAME=Josh Stagg
POM_DEVELOPER_URL=https://github.com/stagg
POM_INCEPTION_YEAR=2026
SONATYPE_STAGING_PROFILE=me.stagg
RELEASE_SIGNING_ENABLED=true
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
